const REQUEST_IMAGES = 'REQUEST_IMAGES';
const LOAD_IMAGES = 'LOAD_IMAGES';
const DISPLAY_IMAGE = 'DISPLAY_IMAGE';
const CLOSE_IMAGE = 'CLOSE_IMAGE';
const DISPLAY_ERROR = 'DISPLAY_ERROR';

export {
  REQUEST_IMAGES,
  LOAD_IMAGES,
  DISPLAY_IMAGE,
  CLOSE_IMAGE,
  DISPLAY_ERROR,
};
