const REQUEST_IMAGES = 'REQUEST_IMAGES';
const LOAD_IMAGES = 'LOAD_IMAGES'; 
const RESIZE_IMAGES = 'RESIZE_IMAGES';
const DISPLAY_IMAGE = 'DISPLAY_IMAGE';
const CLOSE_IMAGE = 'CLOSE_IMAGE';

export {
  REQUEST_IMAGES,
  LOAD_IMAGES,
  RESIZE_IMAGES,
  DISPLAY_IMAGE,
  CLOSE_IMAGE,
};
