const DISPLAY_IMAGE = 'DISPLAY_IMAGE';
const CLOSE_IMAGE = 'CLOSE_IMAGE';
const REQUEST_IMAGES = 'REQUEST_IMAGES';
const LOAD_IMAGES = 'LOAD_IMAGES'; 

export {
  DISPLAY_IMAGE,
  CLOSE_IMAGE,
  REQUEST_IMAGES,
  LOAD_IMAGES,
};
